package config

type ServerConfig struct {
	ServerProtocol                         string
	ServerUrl                              string
	Generator                              string
	CopyrightOwner                         string
	AttributionUrl                         string
	LicenseUrl                             string
	SupportEmail                           string
	EmailFrom                              string
	EmailReturnPath                        string
	ApiVersion                             string
	Status                                 string
	StatusExpectedRestoreDate              string
	StatusAnnouncementUrl                  string
	MaxRequestArea                         float32 //The maximum area you're allowed to request, in square degrees
	TracepointsPerPage                     int32   // # Number of GPS trace/trackpoints returned per-page
	DefaultChangesetQueryLimit             int32
	MaxChangesetQueryLimit                 int32
	DefaultChangesetCommentQueryLimit      int32
	MaxChangesetCommentQueryLimit          int32
	DefaultChangesetCommentsFeedQueryLimit int32
	MaxChangesetCommentsFeedQueryLimit     int32
	MaxNumberOfNodes                       uint32
	MaxNumberOfWayNodes                    uint32
	MaxNumberOfRelationMembers             uint32
	MaxNoteRequestArea                     float32
	DefaultNoteQueryLimit                  int32
	MaxNoteQueryLimit                      int32
	MaxIssuesCount                         uint32
	MaxTraceSize                           int32
	PostcodeZoom                           int32
	ApiTimeout                             int32
	WebTimeout                             int32
	UserBlockPeriods                       []int32
	UserAccountDeletionDelay               *int32
	MaxMessagesPerHour                     int32
	DefaultMessageQueryLimit               int32
	MaxMessageQueryLimit                   int32
	MaxFollowsPerHour                      int32
	MinChangesetCommentsPerHour            int32
	InitialChangesetCommentsPerHour        int32
	MaxChangesetCommentsPerHour            int32
	CommentsToMaxChangesetComments         int32
	ModeratorChangesetCommentsPerHour      int32
	MinChangesPerHour                      int32
	InitialChangesPerHour                  int32
	MaxChangesPerHour                      int32
	DaysToMaxChanges                       int32
	ImporterChangesPerHour                 int32
	ModeratorChangesPerHour                int32
	MinSizeLimit                           int32
	InitialSizeLimit                       int32
	MaxSizeLimit                           int64
	DaysToMaxSizeLimit                     int32
	ImporterSizeLimit                      int64
	ModeratorSizeLimit                     int64
	MessagesDomain                         string
	MaxmindDatabase                        string
	NearbyUsers                            int32
	NearbyRadius                           float32
	SpamThreshold                          int32
	DiaryFeedDelay                         int32
	DefaultLegale                          string
	AttachmentsDir                         string
	LogPath                                string
	LogstashPath                           string
	MaptilerKey                            string
	MemcacheServers                        []string
	NominatimUrl                           string
	DefaultEditor                          string
	OauthApplication                       string
	IdApplication                          string
	ImageryBlacklist                       []string
	OverpassUrl                            string
	OverpassCredentials                    bool
	GraphhopperUrl                         string
	FossgisOsrmUrl                         string
	FossgisValhallaUrl                     string
	WikidataApiUrl                         string
	WikimediaCommonsUrl                    string
	LinkifyHosts                           []string
	LinkifyHostsReplacement                string
	LinkifyWikiHosts                       []string
	LinkifyWikiHostsReplacement            string
	LinkifyWikiOptionalPathPrefix          string
	GoogleAuthId                           string
	GoogleAuthSecret                       string
	GoogleOpenidRealm                      string
	FacebookAuthId                         string
	FacebookAuthSecret                     string
	GithubAuthId                           string
	GithubAuthSecret                       string
	MicrosoftAuthId                        string
	MicrosoftAuthSecret                    string
	WikipediaAuthId                        string
	WikipediaAuthSecret                    string
	ThunderforestKey                       string
	TracestrackKey                         string
	TotpKey                                string
	CspEnforce                             bool
	CspReportUrl                           string
	AvatarStorage                          string
	TraceFileStorage                       string
	TraceImageStorage                      string
	TraceIconStorage                       string
	AvatarStorageUrl                       string
	TraceImageStorageUrl                   string
	TraceIconStorageUrl                    string
	TileCdnUrl                             string
	SmtpAddress                            string
	SmtpPort                               int
	SmtpDomain                             string
	SmtpEnableStarttlsAuto                 bool
	SmtpTlsVerifyMode                      string
	SmtpAuthentication                     string
	SmtpUserName                           string
	SmtpPassword                           string
	Matomo                                 string
	SignupIpPerDay                         int
	SignupIpMaxBurst                       int
	SignupEmailPerDay                      int
	SignupEmailMaxBurst                    int
	DoorkeeperSigningKey                   string
	DBHost                                 string
	DBPort                                 int
	DBUserName                             string
	DBPassword                             string
	DatabaseName                           string
}
